name: stats
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - statsmodels
  - matplotlib
  - plotly
  - pystan
  - fbprophet
  - gluonts
  - pymannkendall
  - seaborn

